name: lamp_app
description: IoT Lamp Data Monitoring App with Firebase Integration
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.0.0
  animations: ^2.0.0
  intl: ^0.20.0
  firebase_database: ^11.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
# [Auto-Sync] Diagnostic check passed at 2026-09-01 13:21:34
